### ISSUE TITLE
quoted atoms broken in Chrome

### ISSUE THREAD

**Issue by Anniepoo** [LearnPrologNow/lpn-swish-proxy#1]
1. start lpn-swish-proxy normally with swipl proxy.pl
   ?- server(4000).
2. Browse
   http://localhost:4000/lpnpage.php?pagetype=html&pageid=lpn-htmlse7

in Chrome Version 40.0.2214.91 m on 64 bit win7

Look at Exercise 2.2
OBSERVED: 7 facts/rules in exercise
1. click swish button

EXPECTED: still 7 facts/rules
OBSERVED:  code terminates at closing quote of McGonigal

house_elf(dobby).
witch(hermione).
witch('McGonagall
1. Repeat step 3 using Firefox 34.0.5
   OBSERVED:  Code appears with 7 rules in swish, it's not cut off

Note that this has been reproduced on at least 3 machines so far, one each mac, windows, and linux.

To Jan for at least some direction, as none of us has dug into the innerds of the swish-izing.

**Comment by SiddhantArya** [comment]
This issue is also the same for Safari Web Browser.

**Comment by JanWielemaker** [comment]
Thanks.  Quoting s sometimes even more complicated than you might think :-(  Turns out that encodeUIRComponent() expects you to use double quotes for the attribute value.  Fixed in
09825c72dd9a5d02cdbe55ae264579fed1385079
